// export const ADD_CITIES = "ADD_CITIES"
export const START_ADD_CITIES = "START_ADD_CITIES"
export const ADD_CITIES_SUCCESS = "ADD_CITIES_SUCCESS"
export const ADD_CITIES_FAILED = "ADD_CITIES_FAILED"




export const REMOVE_SHORTLISTED = "REMOVE_SHORTLISTED"
export const SHORTLIST_CITY ="SHORTLIST_CITY"
export const DELETE_CITY="DELETE_CITY"
export const ADD_NEW_CITY = "ADD_NEW_CITY"